spring:
  application:
    name: "Bingo Project"

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/bingo_data
      username: admin
      password: root
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
