spring:
  application:
    name: "Bingo Project"

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
